configure:
  endpoint: "10.16.1.6:9000"
  accessKeyID: "kotkit"
  secretAccessKey: "kotkit-test"
  useSSL: false

name:
  VideoBucket: "video"
  CoverBucket: "cover"
  AvatarBucket: "avatar"
  BackgroundImageBucket: "background-image"


expiryTime: 60